<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>com.javacode</groupId>
        <artifactId>Neoflex_project</artifactId>
        <version>1.0.0-SNAPSHOT</version>
        <relativePath>../pom.xml</relativePath>
    </parent>

    <artifactId>calculator</artifactId>
    <version>0.0.1-SNAPSHOT</version>
    <name>calculator</name>
    <description>microservice_calculate</description>

    <properties>
        <openapi-generator.version>7.8.0</openapi-generator.version>
        <springdoc.version>2.8.9</springdoc.version>
    </properties>

    <dependencies>
        <dependency>
            <groupId>org.openapitools</groupId>
            <artifactId>jackson-databind-nullable</artifactId>
            <version>0.2.1</version>
        </dependency>
        <dependency>
            <groupId>jakarta.validation</groupId>
            <artifactId>jakarta.validation-api</artifactId>
        </dependency>

<!--        чтобы видеть сгенерированные классы, если не будут подгружаться-->
<!--        <dependency>-->
<!--            <groupId>com.javacode</groupId>-->
<!--            <artifactId>calculator</artifactId>-->
<!--            <version>${project.version}</version>-->
<!--            <classifier>openapi</classifier>-->
<!--            <scope>compile</scope>-->
<!--        </dependency>-->
    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
            </plugin>

            <plugin>
                <groupId>org.openapitools</groupId>
                <artifactId>openapi-generator-maven-plugin</artifactId>
                <version>${openapi-generator.version}</version>
                <executions>
                    <execution>
                        <goals>
                            <goal>generate</goal>
                        </goals>
                        <configuration>
                            <inputSpec>${project.basedir}/src/main/resources/calculator-api.yaml</inputSpec>
                            <generatorName>spring</generatorName>
                            <apiPackage>com.javacode.calculator.controller</apiPackage>
                            <modelPackage>com.javacode.calculator.dto</modelPackage>
                            <supportingFilesToGenerate>ApiUtil.java</supportingFilesToGenerate>
                            <configOptions>
                                <delegatePattern>true</delegatePattern>
                                <interfaceOnly>true</interfaceOnly>
                                <useSpringBoot3>true</useSpringBoot3>
                                <java8>true</java8>
                                <dateLibrary>java8</dateLibrary>
                                <useBeanValidation>true</useBeanValidation>
                                <openApiNullable>false</openApiNullable>
                                <useBigDecimals>true</useBigDecimals>
                                <bigDecimalAsString>false</bigDecimalAsString>
                                <serializationLibrary>jackson</serializationLibrary>
                            </configOptions>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>
</project>