spring.application.name=calculator

# Данные для расчетов
credit.base-rate=15.0
credit.insurance-cost=100000
credit.insurance-rate-reduction=3.0
credit.salary-client-rate-reduction=1.0
credit.min-final-rate=5.0
calculation.months-in-year=12
calculation.percent-divisor=100

# Коэффициенты для расчета ставки
credit.rate.self-employed=2.0
credit.rate.business-owner=1.0
credit.rate.mid-manager=2.0
credit.rate.top-manager=3.0
credit.rate.married=3.0
credit.rate.divorced=1.0
credit.rate.gender-age=3.0
credit.rate.non-binary=7.0

# Возрастные параметры
credit.age.female.min=32
credit.age.female.max=60
credit.age.male.min=30
credit.age.male.max=55