spring.application.name=microservice_calculate

# ??????? ????????? ???????
credit.base-rate=15.0
credit.insurance-cost=100000
credit.insurance-rate-reduction=3.0
credit.salary-client-rate-reduction=1.0
credit.limits-min-amount=20000
credit.limits-max-amount=5000000
credit.limits-min-term=6
credit.limits-max-term=360
credit.limits-min-age=18
credit.limits-max-age=60
