spring.application.name=statment

# Server configuration
server.port=8082

# Deal service configuration
deal.service.base-url=http://deal
deal.service.get-loan-offers-url=/deal/statement
deal.service.select-offer-url=/deal/offer/select

# Validation configuration
validation.credit-data.amount.min=20000
validation.credit-data.age.min=18
validation.credit-data.name.length.min=2
validation.credit-data.name.length.max=30
validation.credit-data.term.min=6
validation.credit-data.term.max=60
validation.credit-data.pattern.name=^[a-zA-Z?-??-?]{2,30}$
validation.credit-data.pattern.passport.series=^[0-9]{4}$
validation.credit-data.pattern.passport.number=^[0-9]{6}$
validation.credit-data.pattern.email=^[a-z0-9A-Z_!#$%&'*+/=?`{|}~^.-]+@[a-z0-9A-Z.-]+$

# Logging configuration
logging.level.root=INFO
logging.level.org.springframework.web=DEBUG
logging.level.com.example.statement=DEBUG
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n
